spring.application.name=tacl-auth-service

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/tacl_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# JWT
# ===============================
security.jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_CHANGE_IT
security.jwt.expiration=3600000
